language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
services:
  - mysql
git:
  depth: 3
before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]]; then phpenv config-rm xdebug.ini ; fi
  - composer update
  - mysql < test/sql/generator-example.sql
script:
  - phpunit --testdox --bootstrap vendor/autoload.php test/
after_success:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then phpunit --coverage-clover build/logs/clover.xml --bootstrap vendor/autoload.php --whitelist src/ test/ ; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then php vendor/bin/codacycoverage clover build/logs/clover.xml ; fi