language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
services:
  - mysql
before_script:
  - composer update
  - mysql < test/sql/generator-example.sql
script:
  - phpunit --testdox --coverage-clover /tmp/coverage.xml --whitelist src/ --bootstrap vendor/autoload.php test/
  - php vendor/bin/codacycoverage clover /tmp/coverage.xml