language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
services:
  - mysql
before_script:
  - phpenv config-rm xdebug.ini
  - composer update
  - mysql < test/sql/generator-example.sql
script:
  - phpunit --bootstrap vendor/autoload.php test/