language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
services:
  - mysql
git:
  depth: 3
before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]]; then phpenv config-rm xdebug.ini ; fi
  - composer update
  - mysql < test/sql/generator-example.sql
script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then phpunit --testdox --coverage-xml /tmp/coverage.xml --whitelist src/ --bootstrap vendor/autoload.php test/ ; else phpunit --testdox --bootstrap vendor/autoload.php test/ ; fi
after_success:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then php vendor/bin/codacycoverage phpunit /tmp/coverage.xml ; fi