language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
services:
  - mysql
git:
  depth: 3
before_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.0" ]]; then phpenv config-rm xdebug.ini; fi
  - composer update
  - mysql < test/sql/generator-example.sql
script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.0" ]]; phpunit --testdox --bootstrap vendor/autoload.php test/ ; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then phpunit --debug --verbose --coverage-clover /tmp/coverage.xml --whitelist src/  --testdox --bootstrap vendor/autoload.php test/ ; fi
after_success:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then php vendor/bin/codacycoverage clover /tmp/coverage.xml ; fi